apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: withings-collector
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:6ofKbVb36uEQRZq2+hZtDk6hdzM=,iv:iGtwaOQtHgSoObQcaKrm1x+hzqYj28xfi5FJXmjhzAU=,tag:4s6BZj8Psy9lxMObifPzDA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:QYEHjU+Ij0JxYV1PqbtEIL1pDPxsIuPI88LN5uGdl+m5oiOR3rUtjw==,iv:2iG2SqTPoiVm7io3fDtjqjEfrfLJHaW7HEDIGVI6nJg=,tag:fRwbgPwR9EvMApUm1cAiuA==,type:str]
    region: ENC[AES256_GCM,data:HpU8fYABKto2,iv:2lbNLzH/ZkKfPGl8ooLjkJqMgDWmrHAvD9NS3eQn3IM=,tag:juyUH4/OV3CSkIx2JBny4A==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMFZDaGRXamJRZHNKYzBR
            N2pSRC9qbk1RejN3MzExZDB4emNINjRlWFdvCnJZU3M3WnpnbjBkdmNCVlZGd1Fu
            UE5WUUMrMVA3bWdjQlZPNEZEUXZNSVEKLS0tIDE4cEpJdG55Ui94aVJNaTAyUUh6
            VWlEZmRTOG1FdjQ0ODZTUEVCM0hsWUEKUE8HDr+gC6U28dNmhC6Cwnlfvca6UM3/
            Kyacgy1O9bg4bj5kOdYlwL6G9sVpO5CRyLiklXtHjCUf0R50c3e+7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T23:15:05Z"
    mac: ENC[AES256_GCM,data:AtGKuI9qdag/t8UhZCc7cFA42RqMyoHZ41jmXg+dLh43+MxUtLYpf52571lXe7tBkSpBidtb/xOjOr8yQzw0/M5gXOuED3ZS8C1TWv6StAworeZN56UlWvvCkRWGalOvpdjcTbvgxMxcY0WIMEX9SiEPlrtbVhowg/4RjfAJ/A8=,iv:fOsIXS/eshj9ZvTY+hR8rlfi91tcTe+eHNwJtJ5uDo8=,tag:izmFbkgU4SyMl4MnngBWzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
