apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: withings-collector
data:
    credentials.json: ENC[AES256_GCM,data:zCdWqWhDZRwxakd3GOWlT9jNfIRQ1g5CTDcvKhTYqMsPywP5W9ck1m4e0Fn/BBJWHurf10IDgSJIVsn3sfzen/Bb+OO2UiCiZ2amDw4hvQF1Ox6bURex+3hoyEaSb3zHlhjgUQSTfzHOx4/k2ZGFB16GQEZNPpdDew1EHycR11I8tdQa2WzOYSgiSl9914yBaoxIcvXQlKwk8cwNcKgWLSzrcdACV0It4T6/4k7EL6VDOlWMBpvOe4iGvxSYSDPuG5effEjGBcGD1J5evD9Cs0xsMmcNpquTJSAzRcOIpZuEkaPlBhnQAh4XBYA=,iv:UwCKCJt7mWyUGLjcHmZLA5/fbyn6n091hZltqgdWWns=,tag:pFgPOROswt9fccKIlavnlg==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubDh5KzN1Qm0rUHNRY2pt
            OG43NTRiOVozQkhTKzVRUWJhWVQrSVZsZERjCklzVDQxTlZZMW1aNnFNTXRIOHJY
            cE5qK3F5QW5tYUhVUzJuSlVJUTc0TEEKLS0tIFQ1TkdGZDhnVkFaeU5xeUdqOERS
            VTNxU1poUVN3dWJhU2hRYlo0dDZlSE0K4R62UZBJeeGGAQUSWaC41uxqX7x3KHF+
            t+4xRyY68t1NgG7WTdgiTSnupKUrJzaG1psPUVEvJUyEyfFierB9Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T22:39:35Z"
    mac: ENC[AES256_GCM,data:W0ZcHzayRMbS1q9ExPQ1I9NVjbpeZUlc9xdlM/+5kIstvsxGlWY6+BrI1gkWbQdAT8LykcIzPCVOBkTGu2Zk/xJRAySKx/q+ifA1Z+twNQseM4nj4G33j6urzOaMXhSAB3M6yPXTzCEjA/fYATEtwrc/j13UKkqrdQG/EKFe968=,iv:P7pnbYYMP99HS5jW0Vf9upN7hfmDO4WoOGgt+y5wgks=,tag:dfqHv4Fy5X7c7m9nV6c4cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
