apiVersion: v1
kind: Namespace
metadata:
  name: ai-mastery-path
  labels:
    app.kubernetes.io/name: ai-mastery-path
    app.kubernetes.io/part-of: lztechnology
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
