apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: ginger-hoa
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:NbsjOL8VpTBC/D+H1+CH1TjczDY=,iv:jYo6uQSXXWMRRMSQ4qA6RdGVUec/HSs9rmXSz3A8pAw=,tag:tknQ2TsAdwTAk5Ot+5x32Q==,type:str]
    secret-access-key: ENC[AES256_GCM,data:wckfInWAGW2hWy6XL9CFwjPZfVcW5tCZcPKrqa3iZKAexR6bTYeOhQ==,iv:9GwYheubxPxguBcNhxYW9Ho2HaCr6hJ46SM5htNJjIc=,tag:3uF/UiILcDNj6ayrmcN3Vw==,type:str]
    region: ENC[AES256_GCM,data:Wld7xCcz+E5N,iv:2MrTVwR6A+H1grIf9SymSJGJLdtyDq1oqQw8FiW3C9c=,tag:BUWdLFPRBkkHwNTg5j5fqA==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M3RhcXkzSHpBUk1UZjFG
            ZnA4REFnL2lSUG80bU9sTURxeTFHWHpuMm1jCjJDWWhXZTFpazE1M244b2hadkx2
            UEd6WW1uSURPQnF2aXpLSHRVc2pQKzAKLS0tIG5WeU9TaFpDTXpqZUM5dnE4dkFY
            Y3BQcTMxTDAwRks0bHhWeFFZYVR3TWsKgt2loQZN6rzzfE3+NueduigaGJnkpG3Q
            kT3vFutyymLcCZbbbjVCfRCAS94tHLcZyP5/Z1pa/VsWMHwT5uF0XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T20:54:39Z"
    mac: ENC[AES256_GCM,data:li9FDUO3o1uVnTt12DUNFCGRlng8aUDLWg0welczu0NhVdbc689Ys9dgmZvHz/DAJ5SxNuQgqQjfnu+5U/MciGBUsDyrbNK113wAmp31X3cNvQHymnH3UQEoDAek3WeIEGOCBvFT33YCle9PO6Id5gkbj6IxTSyWivZEjsZtVdI=,iv:RmGYB3n5VSg/s/FWSr8fcaWQj8TDtRA8XfWfpAHDNII=,tag:qlE/nenDWEyg+rHgnUTiTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
