apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: ginger-hoa
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:QLnUeYjg1YX1x2R2cALS7mOtf8hibcYPGNRpNrnl6sUKCoDCELBcDAzLJP7YxnxwluXdNg7FV64J2o92NSfb4wLG9VXqDGYT2PImKZrAMwnSlCXeY6kWgOw166dhmLjWZSZCNzsrJpxqOqONlTXBKxe8nMqeGj3v8fU9vkFappnAFoLdm93gHSSh4gj6TppRDXXv0rcK18L6MPGAv0rOEYrW,iv:Dr5ES3z+amshkBv4yDPdE3RVHjI4Z/S4JJMdtJkPT94=,tag:AW2pkirvGH5mxVra/AEH5Q==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT1o5eDV3bGk1TVM5V1RT
            ZUZiYWQrNGtmVWlEaWZSNXBBQjhyK2JjKzNNCjJSa01sZ0w4MTVtU3VCcm5XTTVl
            bFJEU1dkU1czTVFEQjVieUNSMzZXREEKLS0tIC9HcGpkbkdjd1JNTHF5d1NJQWEz
            dEJTMHJFTENHQVRxYzRWaWo0RUVJbkkK3SwvZX/dz9C8D08hInCtIqyAqCHom7GZ
            RvUWtsTlqrIonlr4b99P/fSB/j8BDDJaXOar8GPyR0kXvCgmq6hNvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T20:54:39Z"
    mac: ENC[AES256_GCM,data:dRnC2ysarKVTwU5CCILkZOsU93zERD6EJM2TlJ+EzbaULi8DarQgUC24ndIL2iKQAMpzjaAArvLiykpJkIZp2bWG0kv9VYKfsmOL20+kDdAFABqEb1jPHfzGVES8HvwGbx7NRihAj9HVmUmHHCLpyuJtZvTIWXbv0Ym6WZTqiQM=,iv:lgF1JJSsT9761tRvFcG+eNDo7wIIjmLkQjpDIrGewRQ=,tag:nM3jPiSAigvx8wxkEA2spw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
