apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: tldr-pipeline
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:2T6aZa+dQIOUVtPrJ2ppoOMdoFk=,iv:X7BJj0DLfy/SowS4RMpylM5lhTLbOdxwKAGgl59Gh2w=,tag:wVmYbyXOSjsB+jC1SUdQtw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:evjyreFxvgXSt+jSW5I1Pb+WF87IygvRzC0cBI+rJNxojKLoyqRYpQ==,iv:HW22eCnQyAI/VKnRlZLO0eT8DAVuE4H5HiiVIwElZtI=,tag:HRZqTtSAqZea4dV46M5Exg==,type:str]
    region: ENC[AES256_GCM,data:lGVMHmM04FPd,iv:PKcX4Lv04iMKyeHAHd3PC21I2T6VtF+NRMSFdI3eGVs=,tag:rKdGntgYi9SG8RskNvDR5g==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcnN6QlcvN1Fhc3RPSi8v
            N2FVY2tCSmxqcFlwRzNvdkxwZ2lFOERRbnhjCkJQMWN2NjFzRHVTMytDYXZiQklO
            dm94OUtyc0tZMi9KdnVUWFpvSDRQbEkKLS0tIE1Hc29iWGRrTWM4Z3g4YW5rNUQ5
            bnpOYWI5UEJ2RkFTcXJRbTlKSGdDZ2cKkYKl7gNoaOYxzsPu6g8pApUNffpWSpJl
            +GVjrC+aOSHqVzu5usNWXTVrAmH3DWCCUfbdBSR2lMLprUGbPkNenw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T11:49:18Z"
    mac: ENC[AES256_GCM,data:d4xRfFc1/mK0bNiol/sHeSfK7gEeiuIHIEzo+CVsJGPnSJlOnhVHkVnzvKroU36VqS78yyPR+/ycgNOc0y/BkEuxSHEEGUguXuOWnKTE+cAvtiLO+1FTdv8/mYM52DdvAjrGcTgveF8VnLjHMOc1XiIxVS9KksmkhuVmHoaQM30=,iv:5ItBgKUH5KpRkZJDlb2NADxzw5F97XXZLKlbNfESmWQ=,tag:2UVqXLyZAu3xQl+Tn8g1yQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
