apiVersion: v1
kind: Secret
metadata:
    name: apisix-provider-keys
    namespace: apisix
stringData:
    OLLAMA_CLOUD_AUTH: ENC[AES256_GCM,data:TM63ENqIMni8TTyC7pvKdNAdm4dFZjaHOEfyo2k3DoQBfEABJvxP+0wJUVYd1/sIHpRxytAcnkyfsqgzQ032vQ==,iv:v82YaUcPEsu0YX6t9d54BkqfWh7y0HKzzs0Z68hLSK8=,tag:Bmr73oCyhTMbE0R/qMssxA==,type:str]
    APISIX_KEY_SOCIAL: ENC[AES256_GCM,data:gdSMvOTrip8WPEkuurvT0GmnhNmedTw20rCoqbA02JFK81XY3Qt8Jt/uVwUrbg/tGv+/hw==,iv:LpalcZsNc6mWC3B3H/D4/XSR9TtSJ9NHUZs6vNmsWuQ=,tag:jF7qe9NwUy4Hv1QuF7dM0Q==,type:str]
    APISIX_KEY_CLUSTER: ENC[AES256_GCM,data:nCiRIC9f5wsuZk31RvkyZQGRXjBXiDOS2lB+ltz/o/2vSNkpo9YCA2FzHwvcp5aiWV0QJA==,iv:OZYGO4nlsJD7JAiUChi0lPGmuyDM5qkRTJxhGYBKHVI=,tag:/6Nj4IeVJ8DDbF32RUkW7g==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT3c1UnZsUU12c2NkUHBl
            ZktTanNVMEdkZnFRUko4dnlvanpscWtIREg0CnQzZmdLT0NqM0VSRWNRZW5qYjl0
            OUMybUI4SExneENxaUFLdmJwMDhncDAKLS0tIEkwcW1GNUIweFkzZUxtSmdWRUZC
            Y2UyZW9JSG9NUXFDQXZVMTl4Y2pBY2sK1JFPLHZZ6YeAwgfQzXBtswcJSPfUerfg
            iel636IMIjJSjUsfEMvwRWc4fA+r2QbZACvTvhGcVsyL8J+4C3cLOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T10:02:57Z"
    mac: ENC[AES256_GCM,data:xwOioSNibGjpw56p+UJPxOx0aFfsFrm02EyjhVyDSBXDQaydTwp8HZdVLLB0g5v4EIo6aKcKXolfGoBB5ggWy3vMP8CJp0dT7Y7graIzTko9YJQnpuGahUxwcNh2FTefEMWZuvn2coIIOACWRTlIYfgau4CJPmXN+PSdHQ4WeNc=,iv:VuIS/WPuj+dIXi6xLCdFIgWs0M3Gs/mWanl6RX1GkO0=,tag:/QuDis+hIuaVg7eB8USiCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
