apiVersion: v1
kind: Secret
metadata:
    name: apisix-provider-keys
    namespace: apisix
stringData:
    OLLAMA_CLOUD_AUTH: ENC[AES256_GCM,data:TM63ENqIMni8TTyC7pvKdNAdm4dFZjaHOEfyo2k3DoQBfEABJvxP+0wJUVYd1/sIHpRxytAcnkyfsqgzQ032vQ==,iv:v82YaUcPEsu0YX6t9d54BkqfWh7y0HKzzs0Z68hLSK8=,tag:Bmr73oCyhTMbE0R/qMssxA==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT3c1UnZsUU12c2NkUHBl
            ZktTanNVMEdkZnFRUko4dnlvanpscWtIREg0CnQzZmdLT0NqM0VSRWNRZW5qYjl0
            OUMybUI4SExneENxaUFLdmJwMDhncDAKLS0tIEkwcW1GNUIweFkzZUxtSmdWRUZC
            Y2UyZW9JSG9NUXFDQXZVMTl4Y2pBY2sK1JFPLHZZ6YeAwgfQzXBtswcJSPfUerfg
            iel636IMIjJSjUsfEMvwRWc4fA+r2QbZACvTvhGcVsyL8J+4C3cLOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T10:17:14Z"
    mac: ENC[AES256_GCM,data:wvHdsxFitF4Jr9Ho5T4tAjCz5zdPYmZbQygtebBsUvWrjIGE8Y8gSAcgm+i9ntNf0Cj+4CcSK53j6UE97fBi5qhtLxkvFW0zEpPgA8t5UzWiB99j3YnA4ILT3I8mfjMcBETKj5iIF7J3JiH7APsV2IRhyfQz6KbYMV52bzGfeAM=,iv:+Wg0ufCJ0yreFDjbmdLcdnkB9GjPcYguwMFrG/WkC0U=,tag:laZZtS1ZeIoy067qKLlDTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
