apiVersion: v1
kind: Secret
metadata:
    name: apisix-provider-keys
    namespace: apisix
stringData:
    OLLAMA_CLOUD_AUTH: ENC[AES256_GCM,data:GNGaza8TPybdMdYOMZ0AAYaL6M23CdAfk34Utyq24sl+sBR9mLrKKs5zhtpTz2ziPZ0GHk9ovwjUFFse9H+U/w==,iv:pLXYCBlSpptYTfSK1InwmDQi0oFYRSrIh1k05HnBONs=,tag:42PRrIg2M50LIDY8ADlqDA==,type:str]
    APISIX_KEY_SOCIAL: ENC[AES256_GCM,data:/bNhNlXF6aq0zG0DaknlmTMpheNzPKaVCnBWGSyWF68tr4EWJlutyMSde7HSo605Jp089g==,iv:54QQVt0o2vY559o2fIBYxhyARUoP6NIEXhdm+L2ryxs=,tag:rJf476mmppPtvPC54LW2Pw==,type:str]
    APISIX_KEY_KATIKAA: ENC[AES256_GCM,data:LBbTBHcTnIvgx9Y+e2Au3da3ECDxEqnmSH1Szesqda0=,iv:2zu7D9cMFKKANcbymEw6o3tepltqlA7fnHF7jOs47S4=,tag:RM4O4Sgget1x6N+qyiFahw==,type:str]
    APISIX_KEY_CLUSTER: ENC[AES256_GCM,data:Xs4qxvs7LrbBaFPbiwZSkrCVyxJITLB+VnpoWoS/Qe8Bv+n0u55hFFGl1n3zq8+zaAUvHg==,iv:v01hjF+2OiRVChJw9q0VL3SFLQbGbQJdIvBQxmfIYYo=,tag:kiqHhkpJxTTtp0BQWIBddw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQWF0Y1dmangrRkRWVEFs
            RE1Sa2xWMEoxT2lBZmdLSldHZ1RhMU1LbVhFCnFPUE04aWNEVm5SUkFiVWRIL2hT
            ZjBMcTNvMHh6QUFMOXFOOEQ4SGhkdnMKLS0tIFpRVWg0RUZTeVNKVFBHRGVsRTEw
            WmdjcWlKUEdrMkExdTBxa3d1TDZudG8KEM2LT8IDv8Tj3BDJ3hyu+xeYh4fwJ1VI
            bDHYgOFcKAbQYxhAX2wcwNwJyeuw8YP+z2vqV0oawvTDp5PR/abjNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T21:40:36Z"
    mac: ENC[AES256_GCM,data:DF2TQIcA4aeM5tBlmbz79pPICVAlytHU7S93loqF+cN06HzX9t7mjtABig04oPxB05cDXwsKfe1vL1Cw0x+yjRhU8BY4oSR6KN3CrINbbxcY23dX5bYrWl845Ec68RRCAkkoMTmvOjcHEVZEkHisBs71GzDfiSxjCCmLmAu3Jek=,iv:eX9tft+ApH4cD+fcV6edHThQum9jnv4hvgdqC2DdQ60=,tag:hG7hCDKmi0ZtFf5Ar/Pj+Q==,type:str]
    version: 3.13.3
