apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: apisix
  labels:
    app.kubernetes.io/name: apisix
spec:
  selector:
    app: apisix
  ports:
    - name: proxy
      port: 9080
      targetPort: 9080
    - name: metrics
      port: 9091
      targetPort: 9091
