apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: plaud-collector
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:1N83OOxAJItkCwK/IS/e8gJV8Fs=,iv:zJDLdpF/nEet5EACexnKX1D3kq/ZjRxmk3e1fxbrDQA=,tag:XRHW8rszTC9wzy+YrNK7lQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:96A8HihyYczXwc5Cg+V9tyRaHKTi38oTZmYjca4tp/Na2oCkdpFyiA==,iv:oG4hPAi8t8HFCLJ6QocYaQqUUc2/TZHAJHkbr/qPHz8=,tag:jhQz0oK2XpAZke15SbHSCQ==,type:str]
    region: ENC[AES256_GCM,data:+mECbVJNEMuZ,iv:WZTzXMHulmCfFvBxYmHNeOLfqKiP0YlEfwCgL2S3yL4=,tag:BMkIwzZIp5j1zIvfguFAKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSVpFSy8vdUVnYTdpa0J6
            eXBpWlUwaGNxS3UzS0tnTWpTV2N3c1k0dXlVCjBFNGF5RWF4K2hzY3NocitNMDI4
            dXgwc0tUeDJPUTU1a2ROQWhHZHdxaFkKLS0tIFNuNzRja0EvVG1pWXcrSWFEY3ZM
            REEwclRzNDhHakxnSHFlWjQ2VU5jMzgKnHFcfxkeLr03UI8fEvqs+zdGKcmqlBlV
            2YEij9k0eoa2XBdACXdOLncdsl4kg2y947cAKJd6zTYg3NpUOvVy5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T02:09:25Z"
    mac: ENC[AES256_GCM,data:FVcjD8sVorX/Y6GqewKxWNry/rbL2Sid0AJWaZdoU+jrHhrGcWSVOHu7mokX+CIAlt09/vbrP33djVMIT5uTToTOXIbpZ66+rHQfmObyuJiAZc/7WkXajfWqh48KSYtxrS4s5eVi0LLSW+2o9IPPHSe2g+YZ8sSWt4clw4p5GSo=,iv:PE2DaAWLAikS/MzWHxJV4r521FR8d4uBcoAz4+wAioA=,tag:LBZJU6M9yoNTTxu1Rlftgw==,type:str]
    version: 3.13.3
