apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: arc-runners
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:L7XW8vOH5AfmtcSho1LBy5sxSQQ=,iv:WsMGO9cXQHOy+XkeGw+F94NUrUO9EeiMizay0S+BSls=,tag:QX2k+ghHrVDrCPsjnMNjLg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:kdTS0JPFrdlhxV45NAV4njVVD+zy9hDSdeSY5NCm4V7G7T7f4Q14wA==,iv:Xtk9d9NR/g8KsjKJ1rYSbstqN+62SSKOCYuWvpr9Q5c=,tag:dwiYzYU2MoBSE3JPjy1Lxg==,type:str]
    region: ENC[AES256_GCM,data:lovodImwaRtL,iv:8/9lsW9nnMVrV8o8KRD5LKe5PM1jN+CJ81u7Y0q+01Y=,tag:sZQoToP4mYD/58lvbigfmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V0oySjNTMzZZOHdmMHo0
            NWNVTGRvaStrcUxqZlNObWtEWGpmQnpDWkFZCnFkM1Z6S2RBVjF3NFF2d012YWY3
            UHphL29QUjczRTdLdTBRRUgraEpyWHcKLS0tIEhrUjZwTnhPZWdITi8wak1hQmhi
            bnl5Zld2ZnI0OGxQMC9kWjlvdG8vbjAKorvDIAbrAzHxAwMndvqRoAy2guI5sIIM
            XE5+HJqt1sPOaxsUsR+A6oCivfLA55J6sqCIwaFziVeZ1I2oOXO/vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T01:49:38Z"
    mac: ENC[AES256_GCM,data:+LgykEBGox848qQ5vOy/cg3eG27kC20WBKAdQUrL7W/ep2R491JqD1I2eJxVyerYsfZE7jDmjU62rgdRNvroFNfQciWxJTuaJEWxVGYVUNXE6ro3j1EB8S9Q6tPrXXt4gMzOjp8MdAevM7bbiDFrHX7EbHV7n+bLh/XUhCJLIQk=,iv:DJA3a6j0jmARAwusBX8CdxWmwuk4UQX3Uc2q55Lhve0=,tag:FlorstSnx0bvqm9b+cmlBQ==,type:str]
    version: 3.13.3
