apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: hume-collector
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:l+6xx2gAGDZ1kIqH489fWeayems=,iv:OjByQoBN1EFGtAZBIlTA4OcmfKQrFbxSMDXTFxQq6kI=,tag:BQ/hD4RhCA1gpmd6sA+X+g==,type:str]
    secret-access-key: ENC[AES256_GCM,data:yVUlDLvVGDqb0sNsZoKpDQIBMNHgIpDo5t9xif3kAmohE2jT1RG7Mg==,iv:bLX6qVnwe1yJ2Rl7lTGodO43F+bWea7B1F1r7pqE8Og=,tag:iZ1+M/RzcP7t8MF3hXjgag==,type:str]
    region: ENC[AES256_GCM,data:S9lxygHM2avy,iv:tnMiFG81AIX4TSm/xfpqIYTCVw9Jws7Ijh7+s741v3Q=,tag:j8h5SNapwXHBb6YGS0pseQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcXJVVzk5VVNVWkZPZ2dL
            OGxrZzQ4R1E0UWV6MXNFR3ZHcmZZcUJFeXlvCmM0ZlEvL0hlbkZ6djNRVjArOXdp
            ck9WbHN4ZlROVkk2Y0NreWFpVUVYK2cKLS0tIFFwZFFXejdMcGg1UldCWENIeWlS
            MDg2OVlrTk1saUF5T2xva3dMVkV5SzQKE9XeaqVFtWP8pYkg5vm9vZ58WFZ3/fw5
            TOFlIxmhgjHtRzBfJRddShsnhshD9JlCs3FqKDNcRNsvWcanlRl/Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T12:51:43Z"
    mac: ENC[AES256_GCM,data:gM1hF5Jwuv1rSvwuFCNI8zA2R0+dUQpkm7hI0wTY+LO8VzcSOgio6HS0/f00B0nsXL+kNvQvxRpQuhfa1JBDFbAlWnh/SY0PothT6EBlXamG5y80TTWH1KnKr224oGthMq+UOvZcWqbUbxTJJkqs2Vih8AQ5zLaAIree0OVo4Do=,iv:197vRqzSefoFedJaR7WfBPEs6UKSXLZWi3Ye8u3Ydno=,tag:+mYoh/4maEA7vaWm0+3tMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
