apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: futures-trader
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:RdtxQOjoDv7eyPv+8lgKVVg0FBQ=,iv:wK0DqpEZEi4MNuOzE99JcivDlQsvcsB1TeW7Zs2TT3I=,tag:8aKYMaCIjVYa35i0BPPm4g==,type:str]
    secret-access-key: ENC[AES256_GCM,data:zrCBmaB7Qhhq79Kd+lHP9KxuyMVDMlhUtPs918J5HxJlBxWWW8UldQ==,iv:FhMOaqyCU816sRmiGYS8nHYS9vBYvvCWM3P6+mdhVvg=,tag:STWXW7YA4Y8h4RY/GlSPEQ==,type:str]
    region: ENC[AES256_GCM,data:kWcHXfqplj5n,iv:FSVZHTXEXuO2LVxbOFkC1V5rwyirDsG5ltJsoepAqx0=,tag:39KxsPlij/U2soCslkeZjg==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNFFkeTdYYnFWMWYzQ0xz
            L3RyWDVnK1ZPbEFTTzNFVXBEYWtNbUNRNmlZCm1mZDl4US9vYWJSTjJXWFpNUmRq
            RjhCYURDelovOVF4UVlGRGRtZVhhN3cKLS0tIHBTWHhQU205Q2lMSkVVQXdhdDhw
            ZEZQUERSY0hQMFV4RFlJNkFOWDNMcUUK5CY1uMM49qYgflylzywL5iERRUjB/7We
            6C3J11n/kfW2OHPMxOTLRGOEkDaiksIY8SxgNkihUe8O+TsiaNgrcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T18:23:28Z"
    mac: ENC[AES256_GCM,data:CiNh+tNxH1NkWIZrrmCOcgNoBTeoOnfleL1/q3TgzINSDdFXKGc7kftx/f48avczkpoP2kOyxp2gVIa4wICIMMZE6BFLdm1+VAUUBGbdvOtniIK9zIT1/4axlWUqlUw8aN0ep4PqWNTUdv7Lbr6E79N3DrT5yLn/bQcbhBKrZG4=,iv:JlVhcplQvCLUjEYpRnY1iEYt+2qMCtGiYgvorsFQ6vE=,tag:WdsG0Y2QE6AoMH3sK60OfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
