apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: sports-bets
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:58ykHLtgFDSt9aep5e/hIqYfEwA=,iv:1F/2VD0UXxp6L0BkBMRMFbPeFKutEDbbPVeAHyhs5SE=,tag:HngRq9XN5qK3VRxXyrT4IQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:zxoL2zwqiJHzI8qpc31CrO22Grbs/Hb1HF29s+XDaVBLk5YI2qetYA==,iv:tmBHUTfWQAywsbx4kjLjYTUhLlc1ZcNxYdzgwotszeE=,tag:tTwF0g4GqzOWs1QWkSV1dw==,type:str]
    region: ENC[AES256_GCM,data:mZ3ADGaWVsAz,iv:OlM4GxQTVVKSzWqZoN4PGEYYnqmGcRFVnI6V5KgsryQ=,tag:FYBpnbNB/oC7tIRlwxggAQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNlQ4OEc2VXpPekVKK1Iw
            azlKb3ZVZFo5S2tIaXdHUkRsc1ZUNnNubWdBCncwdlNjVE45NmNFbnNTS0Q1d05a
            cGNudm1JUkJiYVdDaXloRko4ZmNhS28KLS0tIHcybXlEMWpxODh5M1oySDdzcDVh
            RjFlcisxSmd6MThOTW9OV2dlY3JLU28KUWfjVaLfjpsFenIseGVKgMNue+IOdh3h
            VeKZnnO+fguFxNh9M7sCoDmY/iUGW9ZY15llStr8iMd+pjzo88bHmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T13:28:53Z"
    mac: ENC[AES256_GCM,data:tkmpX8fAJ7T/y2nRAYF4lBaK0dt7AVvd7qlaz11Kgzzk9fgG5gj4/yMIjC+Z4fb/WeYduudklnA8xc26uEEQ2Z0mmnbmSPRWuNZ9d36AS/Mj1eF8kQAPRQuwaGnGeMaMPLZyIkY1RebVQEhrXKFaOUA2+DVRZvpSbZfS39BPXy4=,iv:vgQNyRcG3ttYs1B/XzEe4cqq2yjbPClJWrBMtbRGuQs=,tag:8R2L2lMXYCUYTnxsGGLVhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
