apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: sports-bets
stringData:
    credentials.json: ENC[AES256_GCM,data:R67TXKYAPlEBLrFHeDU32o1ehWsbcEK07qWJj3uci6qbepiUAd1tPYe8cQv94x6wFzLPhcM3ZsPpbBryhKKYVigc1zdnbUeM8yycYqt5GuDnDdUemklBcUZX+r+VJgOWcw3urNh9hgefpgpta1U57pSpM7lyzMzNrPkXFwgHrNNcsZC29LovPmvafLwnvA8WTwsJHYxZXNZ04MmT0GCMlzpEndmPOEBf3X76hH6AhQ==,iv:CE3ZZo+OpmuaxhpEP8Ft5r8BCqRQLeCviajXmkOtTPo=,tag:H3tjTLTwrW9l4opSWoYIIA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R05BSmU2THV0OUU1bVZk
            S1l5bXFoSHl3dENybTJlSVZZc0hXcitvOWtBCi9XSU1oU3o2d2ZVMFJocGd6ZDli
            YmNJRXN4MW9xcHJKMXNOOGh4Uk5kYTQKLS0tIDJnY1hiZGtJZ2R6SFpMbjU2NGJW
            WFJERWpIZW5aNzBxV2p0Q3dLaVZEd2MKmvoDcRtLRKeUCXArg8Nf4114Jsnkm2wJ
            w8mlaliGuad0RI/Y8Qc3siojPkDDgjDlbxFqCc1umemcBR718eX6TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T13:28:53Z"
    mac: ENC[AES256_GCM,data:++P22/fPVKaN5MQgHS21EoZHtQFUd3CtLUTU4+oN/gEYD/I5jIKBujBPpmrzFSkBPqcYGWselRPiHbLt3cxp/5XwJ9QLkMalYCim8t4DKmNEQQcNn8TxwUFHi6W9xfc29wNVGAk5S6L70JEKJWJlC5pcC7KGhgTb7yp8qvToMzE=,iv:RorUdEACqSlLsih4gU2sWyFT3f8pA5ceSvOYU6gUpGo=,tag:kgy5TfryJqu0uOnNNPB3HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
