apiVersion: v1
kind: ConfigMap
metadata:
  name: zeroed-config
  namespace: zeroed
data:
  CORS_ORIGINS_STR: "https://zeroed.landryzetam.net,http://localhost:3000"
  METHOD_ENVIRONMENT: "dev"
  LOG_LEVEL: "info"
  PLAID_ENVIRONMENT: "sandbox"
  PLAID_WEBHOOK_URL: "https://zeroed.landryzetam.net/webhooks/plaid"
  PLAID_REDIRECT_URI: "https://zeroed.landryzetam.net/accounts/oauth"
  MCP_PUBLIC_URL: "https://zeroed.landryzetam.net/mcp"
  FRONTEND_BASE_URL: "https://zeroed.landryzetam.net"
  PLAID_TRANSFER_ENABLED: "false"
