apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zeroed-method-webhook-external-secret
  namespace: zeroed
spec:
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: zeroed-method-webhook-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        METHOD_WEBHOOK_SECRET: "{{ .method_webhook_secret }}"
  data:
    - secretKey: method_webhook_secret
      remoteRef:
        key: zeroed/method
        property: webhook_secret
  refreshInterval: 1h
