apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zeroed-plaid-external-secret
  namespace: zeroed
spec:
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: zeroed-plaid-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        PLAID_CLIENT_ID: "{{ .plaid_client_id }}"
        PLAID_SECRET_SANDBOX: "{{ .plaid_sandbox_secret }}"
        PLAID_SECRET_PRODUCTION: "{{ .plaid_production_secret }}"
        PLAID_TOKEN_ENCRYPTION_KEY: "{{ .plaid_token_encryption_key }}"
  data:
    - secretKey: plaid_client_id
      remoteRef:
        key: zeroed/plaid
        property: client_id
    - secretKey: plaid_sandbox_secret
      remoteRef:
        key: zeroed/plaid
        property: sandbox_secret
    - secretKey: plaid_production_secret
      remoteRef:
        key: zeroed/plaid
        property: production_secret
    - secretKey: plaid_token_encryption_key
      remoteRef:
        key: zeroed/plaid
        property: token_encryption_key
  refreshInterval: 1h
