apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: ai-mastery-path
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:pHATKPIM0oa6Aq8cWLlAmcaEpnxveA==,iv:H6IRmNMMho6+fFokU1t3M69z22uVSR1FosYYGi4cCOs=,tag:Pj9pVvvmDALQyUehGJwqXw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:WNkF7BVvgvdDUDYMhahqwli35zaBWA==,iv:0f9GEHSiQ17g2q3dEReuqXuhY5F4ivVb4qnVI7JYPBw=,tag:Jn4Y3vTOuELiBk0zoHaV0Q==,type:str]
    region: ENC[AES256_GCM,data:kuMZxIBQ5XqQ,iv:XcOrF39er2FoBx5bu+KXxmSy1MhVGVBLN2dSYAAECOI=,tag:MgtCyKzY+wKEJ8fFF8MwJQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR2RJakJhMkxlZTd0SEc4
            U2VuTXM0N1hxRWRuRzNYOC9PaEtVOXdEQldZCkJvTG5RU2pjRlJta1gvWXZVN2VO
            MUdnaGxuUnlJc1V0TUZyamZBdWlvencKLS0tIHNkaXhTYlRsQXgzTzJEbWlIQUtN
            dE9QRGJXd2R1K3pHUXdMRmlvN1hidmcKSXbTB+X+n/N8kxmQe9hrWrfziPaWzbfL
            MCRhwHrqVsFpaBekiQmJD7Cnjyt5IO6LE1LfL7p5YpI+wMvHxfFUJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:39:46Z"
    mac: ENC[AES256_GCM,data:wV8ZPY+HD8RqCXE5nk98Ug3/IPq/6qg1f7PbCovesW9xeJYQ9VHOMreFuFu7wmhelS25eogGgWbbETyopRo8fuymSbZltx4Qx5sGfto+w0DYk7/YiMpn+jTFbxAbOno/QLlVMn1c6f78NWc0CiJLfxeT0JQOzQ6Tu/P1dT1V26I=,iv:U6pqoyiY2Q0MqRMEJ2IKqYGO9AYJgIhUzMr3LYfm8Xk=,tag:D8po2YjQ/kxFoFbTVtOVTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
