apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: ai-mastery-path
type: Opaque
data:
    credentials.json: ENC[AES256_GCM,data:dt75CPYaJwOTKf1ygSDyvI1hGLkGbvHOoBRpoWQANH5IEWRsXYVghePtV8Pyj8p6ZbZXFTsAWjcSO+/MHGVcMk5nuVS0/qGVyg7R+ybvf8YAF3E4FOFabMvDFbv/1xH8P9M5B7Y1pc7fa16y2iTrK28w6oj9z8RdN7DmEWrW4U76jTDR9uvaXt4wPSegouftRg0323N7JZWLPBZivbjvs3jnuvgOrOHJUSQDLXc/k1OggUUbi0IsYxoh1SBJdZn3/xqJY1M7za8N7BCJsgimssumurwXDC+BmufzTJwyi5DJ61g7vPs6dTsfCX0=,iv:eBncN/PFmlxbDvD2brr4frI6+8N0rMKNRQG8HVvaUrA=,tag:8et/gt8vOg8J7m1gdNG/lw==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN3JKWVZ4aWFZL1NkZ2V4
            Z2xvVVZONmxHN2VzS3h2bmhCRlA5RUZocG4wCnBnd2pYRE9KTlJnSnlxSUJwTmxV
            V09SYkJvc3ZraXYwdU1NS1ZXM2s5ak0KLS0tIExvSlp3YWVrSmgveFZneVYzOTdp
            dTliNG42a0pzRVJpeXl6RlNCOHUyUzQKiN1ivVYs/qw6/JL53jlUto7PR8M5v8yp
            QbMjja7k+pHlxWbIpwmzwuKmRW6pt68coWvzJTfqNovNer+XknPkHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:44:41Z"
    mac: ENC[AES256_GCM,data:GCOJhvKnrGizg7xPKli/aoisWNtNnBeIglwVeSZ0pLPFwupDx1jKvYRQnfP2EomzWIEJdYnbAjqOdC6wNxaxTs7/W8K4RoOPCJTm0XGnqtp7JlWM0j6beVNLYr0mrAnDlS+o/PN5MkHQAiU78o401k8vleJ42pyJswAyznzmMBI=,iv:IHgmBWOMeJZ+uX3Zmk1qA1b99XcLuTPQ9dBDApMYhDg=,tag:HBJUr1I8EVsZ6JwdLd7s7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
