apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: ai-mastery-path
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Ql9FTv+4N99e0mShHGHY+9Z1CMV72A==,iv:jTy93pqT6/rRbNaMXqIfvvMHFvQTqCMVx5wXyciOlVo=,tag:fXSG5ww1WAtwjaJ3wBKAZg==,type:str]
    password: ENC[AES256_GCM,data:nS6+qvYkHspLpJKYzbknUkwOKLnIUQ==,iv:ySc9OxX61g1AMeGXw/9IL8RIE/DHAVDyMnc65ZczM9I=,tag:r/rw102u3MWElaFhyCqBNg==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWENmd1c0eFlzaUdRYTJE
            QnIvQStIc01yLzMvSXRWM2h6d3VrYVdTVGlZCkdxajNHVFBPZFV3bWJYdHIxZkt6
            c1RzNFVBMTRCN091MjNZd2w0dHo1YmMKLS0tIEJnNEkrSitUUDRuR2hiR09xU3ND
            dUM5WGZPUCtNUlhiek1XMjRhYzllM2MKfGsLnmwgXb1OqEp9HVxHMPECQF3B4/hD
            RkvANBgEgZGCfvg61PugSnoSB4Rg4vqI7VPzqHac3IL9CFPXvoHTfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:39:51Z"
    mac: ENC[AES256_GCM,data:qKJRTbZ2twi6DNvBSLUJohjyU5yhnXRi+8aEkWmZNR3zFg6uq+1yIp4crOR8etJ6EU3eLgRL4A/aUklCaH0LWu5+sXeZL0236C5eKmODb/e61qyvW6R/L3mVtzSGDdOgQ1/h+lmEUdVCpgonnUsjBvFEOnwH/dnQv++ztFO0xUM=,iv:N6BW1clQBvjAb7cboFUpXrUdOaAh6lcX2GBiOOlJYV0=,tag:doVh6/s1ePdZ03ZtaNHLiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
