apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: ai-news
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:IWco5k+5,iv:SoSjGZw+FkapDpmAHwIJQ5LpO//C3otfJx30PKoRKOY=,tag:GKJRqlKJNoVPaMmfWMT03w==,type:str]
    password: ENC[AES256_GCM,data:M2ByPgetCmmB9345mNjGLoXGHko7j/9oC13tNQNg8Ov/2Idn,iv:aLkAtXZJBtXoNlfVsBMjkXssinuFwAciv6REHWeDl/c=,tag:4BFf4JpnHCZDcIIz4LFQVQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMEdQa1d1U3NXeXM5R2hK
            UW5TRU5QWC9ia1gyRFFOdlJaS1I4YWNMejJFCnZ1ZVlxU0J3S2toVDdqdC94MWQz
            UGJoWXVwWisvUjNCNGJQb1hLK1V0RlUKLS0tIDdKbHlJcEZEWk5neTBWeWZSLzd6
            MHlPOUVZcExCU2svT2VlR2pTeDUwR28KYt4PZtiyF4ApdrWsYy/9YsqEO3P6q5qY
            jzrkNHRja2/snMo2zoqpQ93GAdwy1eyRxc5GSLuKy6qzdG8nKgYwOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:17:33Z"
    mac: ENC[AES256_GCM,data:L7/krHMX2uFGGwAyFFR4cMG4qVZ4bMbXujmdJGQMgN9Yj7msr55r3vYP7uAiiCzCHKUAP4nx0qCnwGhnU2D1tdGLF/4C+aa2gvXAZCBTr89PLeYbYje0IkgkdppePkzT0S3Uxg0ooiipDNuzzgJoLg9LtS8cHI0jQLAd1VZ1VB0=,iv:U0UzM7uocgS7E38Nep1LRrPseEAdPxIdtfOcbS17tUY=,tag:X2BV1MCdPA/UyyUHuPmSgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
