apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: lzt-lead-agent
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:Y5ftFfMnS+kIiQd6JpKwcBmHsnE=,iv:qIalw4xHOdc/vMtDdrfiAkNmmuV6jNNZsyQ3XGOW3/s=,tag:c8E/nsEJfetqWq0GzQIAvQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:0V5JgnUtEgGGsRkZ8Rb2M+QSpA92rMuNgCOKjrkpK6o/3y31py7vRw==,iv:GG5vHKvBlunU3ZkrhPYmBhZV/GQQZgpHSYU7v+fwkbk=,tag:BbF99CTt+CmUVfqnAlnpyw==,type:str]
    region: ENC[AES256_GCM,data:r4rqPlFWnGJS,iv:4r50amSUiK3LAOOrkkqbsKIX3upEjOAAXlssnyKnh8s=,tag:u8y10JQfzRjDp5HFvcvaTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENk9hOWpDRDE3WWpQaG9S
            cWFoanhjYlFmT2hWYnNSa0VDM0xMWEpTMFNvCkp2K1Y0bkViQ1NSWUVnVWIyRktM
            S2hlZW9OSHRidWVNRy9uM3lES0kyNVEKLS0tIElsdU9vVnAxTTQyWnhEVmxmTjNN
            K2J5dnV4NVBJOUhnUzZNUVZCL2NTdXMKNkaG3EeqaHe1MXVDnjJi+AtGL5fI9iwx
            2CCTY0k1lEgPKZ5E6uKPJsevtAEIHw+wY/DFkgq4aXGoTFryq5z7lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T17:42:46Z"
    mac: ENC[AES256_GCM,data:FAqLZQlXrEj0Tg822h5U9XdPOhpeXObLtIFLTpEpZQ5ex6lGrQ5ZQlqLo/HgdPcbuY9JlF5goglDyyGW4Ixjy1U39Dxu3aQOat8bOy1Kf7bMDMSib/x4FBdl3zIzvRjghWhyxANSPYgU2n/M3dyuEGpaxs+84nS6McktQq9DgGk=,iv:Lf3KLfnimn3J614PbeY3HpXQKP5xpdVziQOLxD4fBXQ=,tag:a4Z4wTavQUkWY+uTeui+0w==,type:str]
    version: 3.13.3
