apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: housekeeping
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:zSjHKcA+8mgh4i9/K/FwgRsaFBA=,iv:Jm356NsBAcrrj9R+2TtryV6KIa+vNIeUYPe+ZlpMgPg=,tag:LJUmAyvvlH1+L5YGiBnBKg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:q619ucDhFQOBmB/nc4KjgfVRj1U0yXOjW5B1TnD9ncOtrjPs4KsNYg==,iv:9ut22Vy8FH7ba0vW6iCeiUHoWF59cMPSh8G9Z1Z76cU=,tag:PWWT5NfM0KmD/i/+PhTguA==,type:str]
    region: ENC[AES256_GCM,data:Xov9f/GQTwj8,iv:byraJeUmay8+CjdQDHV4E2FdT+Bgm0ogKY3olzn5QMY=,tag:5t17HLUaNjxNVMaHqSgGHQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQTRscjlQQjd4VWw3MDkr
            U3greUNPOFB3ZHpVaVV6emlycGFJOUtMckM4Cko2aUcvdy8yNlRqMEwzSWJIbnk4
            ZGcwQnNPMis2UG01VTJiVGt1b0xyY1UKLS0tIE1BTmkxSDgwVlZ0TDZxdDNXYS9o
            bDZraDlDUjV2cHJSR0I3dnZ6K3FncHcKOItpqNwvNCkYATTrOvDwqzuCJb7qD6N0
            BCEmT0hA2t2wyztjlUbKT0LeOb87hMpC1io4N7IBYH+n5c1XaE8WIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:20:33Z"
    mac: ENC[AES256_GCM,data:S9Br11MPghtmtiI3a0KBGBfFgCn/cSehmUT2XY67PKPTxrNMD3gtu5Uipi13JxAWraU+dSBwvLNDY07rFEp01iHqWIUD8q67NkMTWPEN5QMN8K5KTjMobPDPft4ovF8laUOqiTfiKx9D2J2kZAk93SCEfGqsa2idqDIRihIcT0c=,iv:TlQzPAvxN7K1cloxu1505gyNutFZaYV8MeY7BylsGuc=,tag:DpkYzbv/JvnyAwRXnuEAlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
