apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hume-collector
resources:
  - namespace.yaml
  - rbac.yaml
  - secret-store.yaml
  - external-secret-postgres.yaml
  - external-secret-ingest-token.yaml
  - external-secret-obsidian.yaml
  - external-secret-dockerhub.yaml
  - networkpolicy.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob-report.yaml
