apiVersion: v1
kind: ServiceAccount
metadata:
  name: hume-collector
  namespace: hume-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hume-collector
  namespace: hume-collector
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hume-collector
  namespace: hume-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hume-collector
subjects:
- kind: ServiceAccount
  name: hume-collector
  namespace: hume-collector
---
# External Secrets needs to read the transformed local secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: hume-collector
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hume-collector-secret-reader
  namespace: hume-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: hume-collector
  namespace: hume-collector
