apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: ai-news
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:dgXfD6w6JQByqtWyM0GmnXuY8iU=,iv:uT38k8419bZzybNJEj0d8ufSopvBLkGfpKXOwF3WDbs=,tag:oGCoO2evd91HvB+AEZ7E8w==,type:str]
    secret-access-key: ENC[AES256_GCM,data:C8MAwcAYdg2y4BGGjWrSPb/jgXXb0dacbTj2jH/mwW15XKc6ataKJA==,iv:jxNbYNW9xc/wDlO7hvl2CTJyEETCUAW3kV5rNhlPtAo=,tag:excX7rq7MrQx1+otP1bgaw==,type:str]
    region: ENC[AES256_GCM,data:x2dzn6gWfAAy,iv:MPczSJZNeVKLX+00G2GTOBZreLDpFW9W7QRqXghNmW8=,tag:hnvWnjyhzfD/RxHUiXCzcg==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd0pnMUh5dDh3V2tmUzhy
            NjkvMFM4RzBWZnM4YVpTRkw1WnJsK0xHRER3CmdsYW1RRVFlVWhac0wwaHQ0cVQ4
            Y0ZzTFRFM3h6b2xkMG1DVi9NbFJwUUEKLS0tIEdXZnF0Sm1LRHpCNlg0aWI4ZEZZ
            R0g4MEFZd05zYnE2Ukt4SEd0a0tBVFkKKLDG9oUn9fQ1F5GrTyXdXlziTGpVpSPn
            iIKaE1ly3XyfqOksXqt+wz9Y1rspnyFX7qbVv0B75rH/yWiFJx9IRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:16:58Z"
    mac: ENC[AES256_GCM,data:jFm/KXuO3T4LkReB7+/WiXvOa2QUM2R4uLHD7UtXRVqsd+vvfpiWeteg2a61pNYp6AbdatLmRutr/CcSRdZL/fyhAn0fU+d5nmQ56OPK7Yeaj+/MYkTc3QmGsNilhPDBTpIUyz2xjFcjg5vS1lKkvoNjf8P7m5e6hcDbO2zAatM=,iv:62OMY+MDE4Ty1J1Q5Xgu6PnAiG8+HU/caQwLCjHu6Qk=,tag:MNVbjNSjCZ6DistxsjzJww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
