apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: fieldy-webhook
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: "{{ .credentials }}"
  data:
    - secretKey: credentials
      remoteRef:
        key: fieldy/tunnel-credentials
