apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fieldy-api-key
  namespace: fieldy-webhook
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: fieldy-api-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api_key: "{{ .api_key }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: fieldy/api-key
        property: api_key
