apiVersion: v1
kind: Namespace
metadata:
  name: fieldy-webhook
  labels:
    app.kubernetes.io/name: fieldy-webhook
    app.kubernetes.io/part-of: fieldy
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
