apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: piper
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:E+y47UdmQCgmrIOtbUos2ofiIvg=,iv:dzie/d/zyPmkDgk0go9ZGOCJb+y55iYm/CDykTLaOog=,tag:BdoKYdTRMX087lSQoBHPVQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:M1j32EkjIRMld0ZkamU9srDhBkpX+XfeleE6hGjfXlcvc86dCfGOVA==,iv:BycDv/GLVN68Vm+5P1FdwUkwdaUFC0PaGxx7rXr5Dk8=,tag:0jxZMwZ8OnKhYWpvXggcnQ==,type:str]
    region: ENC[AES256_GCM,data:N+FQBZaJJc5D,iv:9+aFjChZ+YrhzPC6zckBOGuwdJeu8U+CulnHH3u2RLo=,tag:JhxLu3Eoi+I9utbhrmH1OQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWHQ3Vkl0RTJMMmtySVdZ
            UXNZcTdUdXBQblZ5MmE5R2ZMQU9pbzZCaVRrClV4bS9ETW8yRVlKZ0ZaRGlzUEFR
            M0R4L2VCVXBEY1dNR1BqUHprbDFXUW8KLS0tIHdmQmtkMGpBU0RrSy9mT0duSTlL
            WERqa2JzdCtkN24zWGNXLy8rRC9ITVUKv6yJg7rXonuzWUpbO/+Hj+7DFdC3qU3j
            zyOcxTis7B8uZSEECEMBHbIoJ0WVfKoSfAAcJNFRSswlkp4EfaFz4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:20:33Z"
    mac: ENC[AES256_GCM,data:8JemPk1RaNYFmAE2RDOPS2LNytbonAjlHC7kI6EmHDtp/jGMM3WTK4DR6ODf189lMjo7l2MI1E0xM3krBEzNkBM55sJEpZigDiv0okSPtlhD4tdWYXnvhK1IRu7NNShYBzErTFijdZ48u4UXdAQ1RryuRiERat/EtwYHKcwoomo=,iv:w4tNz04v5kFX6yAsm/iIV+uQNYDvfceRoj0HtCaksT4=,tag:8LHt/OPYS7XGJ80UgY0Kkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
