apiVersion: v1
kind: Service
metadata:
  name: schwab-callback
  namespace: schwab-callback
  labels:
    app.kubernetes.io/name: schwab-callback
spec:
  selector:
    app.kubernetes.io/name: schwab-callback
  ports:
    - name: http
      port: 80
      targetPort: http
