apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oura-readonly-external-secret
  namespace: postgres
spec:
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: oura-readonly-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: postgres/oura-readonly
      property: username
  - secretKey: password
    remoteRef:
      key: postgres/oura-readonly
      property: password
  refreshInterval: 1h
