apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflare-tunnel
data:
    credentials.json: ENC[AES256_GCM,data:HRTwJD5fswcaCLuSIWRtDnFKCvzQewmauS+zYEq35opNogq8Ejs3ry2m1JI0oK7lC7H7WgS54CfT40YIOgej11yfiXAZDk/Dn1JT+ftN2XoW8cvTSZkw/L/ZuAHkG/+U8u/LScpJSAOGSJrQHA6i0CkkPXShfs2CfBVtpfPlc2izSxI5BoSLo7cvzCag3aEWELgTyBvRM5m7erHtLrWRAVVC+/lv5rtg/JK5FwMtzEtWV7+HT7ybnJf/lvKlAyGul6fFybGnkItQTrAyTXE1fbel6dqEbpN2p68gTV1zK9x5PM7GhjzNIKLb0ss=,iv:RfWw3FO5T83/+u4iDSqDWU8vV+HvrYqqarX7LEHG0AM=,tag:slC2n8UAV3jS28PJ+lxIwg==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cHFMZGN6TTlTYkJYRjJB
            SmVQMkhFa0lzcGorVmlwRGs1WmpCeWovaDBRCmcwcEFZQ2xwemtKS2hSMkptY2Zi
            UDBpcXVtU0s2eHI5WWRHUFdKQVdyTHcKLS0tIFNmeWZhTExSUnFzZmVCS29yMmQ0
            cmh3VUh3YUdyd1p3QkZSemhlNU42bzQKWf4gEGmGzip6PW28vwcsrwTHwo/8U9ne
            jzHFb55EO/JdsdUgljb9yHpRYfj1DNUM7+3eGYMKWCrGyxO3nxsGMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T11:17:36Z"
    mac: ENC[AES256_GCM,data:M6OtFKKGp1QQpAsPwjGbincoIIzVCsZh/arjjEvf5AjcjXePUwjQj8loZDYEvgOVVQwdgnpD6Op11uIo2c6/bnFcZvBK0vdYoXcR3tAQsCR1nnm+R82DHtO65JDsLyDjJ/um+rpU1N+TkHKbwdk+61wbMx9xd/Z7Fq8W0cwttBo=,iv:fNOVBS7wwIlrAQNh7V69OMKjxcqVcXfu6DDHNzo8yi0=,tag:ddBxhIQ6d+d8RnjcnUmBcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
