apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-blog
  namespace: blog
  labels:
    app.kubernetes.io/name: hugo-blog
    app.kubernetes.io/component: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hugo-blog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hugo-blog
    spec:
      imagePullSecrets:
      - name: dockerhub-registry
      containers:
      - name: hugo
        image: lzetam/hugo:b3422419a0792a16c0498a1da5f735abfe296b45
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: 64Mi
            cpu: 25m
          limits:
            memory: 256Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
