apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: ollama
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:z76DoQh8zrq0PnZQL38o/PHxKsw=,iv:ygroX9d8rXFgpiEDZ8PswNLW82/UoYELMotb2kiFxcs=,tag:Szoe399tdZQJbhf1kJgS6A==,type:str]
    secret-access-key: ENC[AES256_GCM,data:hSUc99iTNpDWtXwiuYAxp582S1H5L57+13pTlaCd+mc8S+LGSfRmFQ==,iv:q64qyeQ3zWhnLBaLE7CS3Dnxpq0mK+4DPJoQs3BO/M8=,tag:0BJs0zO4PU8/rwEks8gGWQ==,type:str]
    region: ENC[AES256_GCM,data:VuWQ5AT4T5cF,iv:JnTmDt1PfYdVj9uBAZVpB1l3ElPXavN/5r/3kGbaxSk=,tag:TXEIO2IMVXUgXjVgLQ+q6Q==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRm5sVlZlY3dDdGVIQ2Iz
            bnBZQUs3MytPMTFJakZUV1dTK0lhT0pqUEZFCnJkZVd0YmtwR01CMGt4RVhkQy9q
            ekdOSmFzbVBhTDRqa3FHWVhOcWRsd1kKLS0tIGlEUXk2NXJvQ3FmNzZwWjdSYTBE
            U2Z1VnRDVUpHSnFSc0gxWVdLdzgvNFUKeCw4RcAz04TL3P4TnirpB2sDa8D75G0P
            vdCcrWDlHB7PeHTRq5miapoKI2DcK+8/eCKSjhbnn4KY+QztbBvt/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:20:33Z"
    mac: ENC[AES256_GCM,data:+A4E/wk3lpxgESQo03L0+ZzKKdKneP2cqYKc5Km3X4ZazMDOZXK5BfxunNHtCduLbbCKQ3eV79+PRNg+r47AIpdFmwr52DjcViW+ajfkhvspmF+anCKJf9BLs2HHFJd7Vxx9jXQ+ASQQHogxVvc2jo7tRzqaQYVJGFU0VcVKjYU=,iv:eXK9raD6Ic39CgRINXHlb3s0xBeYPXUJUM4RXD4cEEs=,tag:kuq87GH/V2jAs57RqM6gHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
