apiVersion: v1
kind: Namespace
metadata:
  name: zi
  labels:
    app.kubernetes.io/name: zi
    app.kubernetes.io/part-of: zi
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
