apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-content-studio
  namespace: ai-content-studio
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: traefik
  rules:
    - host: content.landryzetam.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-content-studio
                port:
                  name: http
  tls:
    - hosts:
        - content.landryzetam.net
      secretName: ai-content-studio-tls
