apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-content-studio
resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret-dockerhub.yaml
  - external-secret.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - service.yaml
  - https-redirect-middleware.yaml
  - ingress-http.yaml
  - ingress.yaml
