apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-api
  namespace: vault-watchdog
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: obsidian-api
    creationPolicy: Owner
  data:
    - secretKey: api_url
      remoteRef:
        key: obsidian/api
        property: api_url
    - secretKey: api_key
      remoteRef:
        key: obsidian/api
        property: api_key
  refreshInterval: 1h
