apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-watchdog
resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret-obsidian.yaml
  - configmap.yaml
  - configmap-script.yaml
  - configmap-ca.yaml
  - networkpolicy.yaml
  - cronjob.yaml
