apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-gateway
resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret-obsidian.yaml
  - configmap-nginx.yaml
  - configmap-ca.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - service.yaml
