apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: vault-watchdog
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:jD/A2qkVt7hgIuvMptZN/mgEP6k=,iv:vtwsq7rkhMabgowBKRD+5Wn7vRJpjj52jMjoYZN7Kgg=,tag:wmPQ89cKEgnYcnOZYluDzA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:SIgKx8al+mnu1Va3vBHH9WYC7uXSMHge9KTVrxDfJhGBCVR+qeI3xQ==,iv:B+eOz74oz9zWHU2Dcm0OgCFwgEBmHdmWlo+e4HGq4MU=,tag:Y31njQ5KAKAsXw7kAABF9A==,type:str]
    region: ENC[AES256_GCM,data:qtFql159bfEp,iv:4Oct5BESNd/z4nK6c4ttmR3aRFBr88I2LgkKElG70Mo=,tag:sDPlbHKskfKQ59F1tWA+3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0djUvWk0velB3Qmh2VjI1
            aFAvekRHaVhwRVNWK1FZU2NCWHNkTHl0RGlRCnlBSmZLQkllK2p6WHRUbGVOK0NH
            T3A2Mnh0SGNmVGw0bTJnaGQ5TkxQSTgKLS0tIGV4YzBNbytCWGdpVmFHQTdtbEht
            eWM3RmNsREdYbGN5bDUyYUhRa0ZBMUEKV2eB61kS6gtX374v8osu/sYxJgtLvJF2
            xYh/jQqGzk/5i64M94UClnMwxPtIvuFc7J3Eimz1/7kaniiBqg+cTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T12:55:08Z"
    mac: ENC[AES256_GCM,data:eB9qwP73jRsnxCnuoTYwZQsAwAgPb5S2vMKBgQXKeDOR2JOMnqg+RO24Yb4Zlb4bC7Ckf3XyFRKeHM/hzteTjNy+eyOwYGgXj+wbRSBVUqNoUxqD64y+uHczZGzH5gadkyOBc1s8jm5XD1wxTbZhL4g7Wr2vz/ZOZi5MF9WoGdo=,iv:Gf5fylLNG0jwKe9mx1TxPYkct4FKJhCb8It4E6YSA2I=,tag:EtHRssjFZJCwUFNrWJkR0w==,type:str]
    version: 3.13.3
