apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: soccer-banter
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:KewF5If8O14a34teazxHGkCOIJY=,iv:liEgMykaTfYuMXblZLyOpyRbQeLzLJ9osZuUwIkHjCg=,tag:XUxqHOy1ri0jIYRZ8ms25w==,type:str]
    secret-access-key: ENC[AES256_GCM,data:cgVTJ8/+klTf3ROxIQiDa+NRG29d7f1aBFFLZzQQO0wMorVh95FMZg==,iv:H3mQ7QoYEsYQL5bYNLVLlzr25tyMQuJj/RPm8AAU/hI=,tag:Hi4yvJ+jkpIzVZO95hVJWQ==,type:str]
    region: ENC[AES256_GCM,data:/z+o7SoOnTzk,iv:7ykeGMuibKvvlLESspoPNK4vq4pwdWZgmbp9qIw+bH4=,tag:kgXJUwfxJsKYVDImuyUkSA==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZU5EVmoxZnEyZEUrVXhv
            Y09obXVLVGZBRnZQZEwyZkUyYS9BaVNHM0hBClJxTTZSRkgwODhsU084UWF4TnI4
            dnB5L0JlWmwvdFhjd2hid25FckZzOVUKLS0tIFllZE9lNTMvTzV2RWtqQUE5NkxC
            SGNNcHkxd05NamxzS3V6dW9VbkM2cWMKEeNzIK8xs5Rqbhz1fI8sDqS+0Ahg4BKj
            k81A2zXiybUr7fax3kSKOheLYZpfPeB/YC2OTnjr6Wd1g1sVRDA2Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T11:23:18Z"
    mac: ENC[AES256_GCM,data:XM38/PumDTOFoWwTy4EHbcFxo8siSLS/+olqawaUpi4bNy50Y5xJIs+wq1JxGPSMWMNoaKHaNGgYk3sPX7oS8e5QncM6nrBV6hxu5bJzNlr+vB6hZQLW9oZslsMncxgbC328KMJUoGpvl+2zcNsfvjwtDrPNPKT5fxtusoHGFko=,iv:l7mBZ+AehMNRVGEaykCNLMhytgfzJZSd1BDE17w4Qnw=,tag:LLavAZEeMFyhmqlhO+syHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
