apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: soccer-banter
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:ZJVp9efqyhI4sV4bZNmfSR0V0ti89CrIwIyhX3WUXRFPLnN3abclTUOgIbGis/zvE5oZVW9D8MIAJ3JUMWJDn3OOOPi5VNqrXTJmEQXeFPEmq9AY/MDwmIqtX4bv7L02OjQ5iOOARpYMtrYYRbtzYdAaT/0sXKPYitqKva0mxg3nEwVsa9aEWIWTqjS3ijOgFwNCwfKTrSJQmmP1Wl9YWxxU/khXCiUlM/g6PKiOZkJDAmAZDSAK,iv:i3deT13+vssUMwl40Z3SUs4jmRwSljXUgzuELPAL+lo=,tag:OXd96ZMQHmHJ4lDWaZsr/A==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V1NsdkNmSlB2TzRLMEVM
            SzVtMFFsM2ZKYXYzRDB5OXdqOU9uTDg0eWtnCmpqYk1Pd0h4dW9ya2NPNFZKMW1Y
            eUVHemRpd254VFpPUDFsTThsZFhETUkKLS0tIGJuYUVlTS9xWjAxVjBKb1dDMG50
            VVBQbDVyVjVDbTlsbjljd1IzdnhZRUUKYWIWtCWqov4/Yj8kH+UMTm6es/MZjSzx
            ikfxxNWSJzSvcvXxEVxJZqm3AIbu5xLYygXIatAGSVuelQHpkDNaxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T12:26:25Z"
    mac: ENC[AES256_GCM,data:ZFlUw+003UWaFTh7PSu79cWWriqTImaLTWQie/WksoXO5cZcWr8rc1Ysz2Q80hGCa9BpyAwZH4aBKIl5FaNU9qEVZuJa8cfPRZkQq9fFaSQjALW5erbkqJxPgZWnuq9ZmIMfmGmAGoaygwtPTopKTdaoj1zl9EZghTPdH0DiXw4=,iv:Z7iHu7RGYHlCw7zYzgCCtgIm8UEdCoPXQ4MdIxKFFVQ=,tag:eIF1J5FI1LbJboPAHXLv8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
