apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ig-inbox-uploader
resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret.yaml
  - external-secret-tailscale.yaml
  - tailscale-serve-configmap.yaml
  - deployment.yaml
