apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: remarkable-ocr
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:6aox1p1FR8hDPZaL60eXP/unBO0=,iv:rua2mCBYD/nWaJIdAnynKtInL/TwVxQ9Kpc72HC0y5o=,tag:2qBAJE8EX80wF4VyajiG3g==,type:str]
    secret-access-key: ENC[AES256_GCM,data:E2n2HpWV0vuRwLjla7e2iVqQgGpFV07vdex84IYx3D2I7U9GujcNrQ==,iv:v3lHlxxkT5MVYoq8FtOdf+VFG6wGJtHoS7j+1PcX5nc=,tag:a9+MKTXAiokB6h9MJ/XFGQ==,type:str]
    region: ENC[AES256_GCM,data:SfbeNQzqdG/o,iv:eGcX2z81azE+eJawgwLIEZOTOVT2QHBpzDkm87pCH40=,tag:BanHk8I872je9NFfsqljiQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRlpXZkRNVkhOOGdRMmRL
            NWR3ejVsamVESGhZbzE1Q20xWkF4cTVTaXdnCk1ucVVwa1BMcDhWREtZQktrUkEw
            aTZQQUhYMGhYcks1QzFhbmVFVElpRmsKLS0tIEl1UGc0RC9oYnFiRmdLWU5QQm9I
            bjJrS0g2MTdnK0NXdGxWK3dMUHl2a1EKRUiAYAsWDpS0GkSqEgMyro3DzMSCAJzy
            SAcRrs/JAdaV3idspe6ehlHqjWvx20OSL9iaspvLgRIdfhxY31Zm/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T10:38:14Z"
    mac: ENC[AES256_GCM,data:KkXt47h8TKSEx5J56j3cIwU9r+G0j4DaRCln2NxxqZoLuLc4wE2uR9/FIUonB1ECQIKUFqLnM5WKCtNqf0UxsUcX97U6ByDwSrwRas3fQ8P7N+zZkJ6Brkdy9cj7udVOD1RfmStQFrrZ47ULhlKWXUGiGvcymXj9RW9PC5VzkSs=,iv:0DRn+OGPCAcBDrivVux51QT1HAM/jmnddhopFsJViRs=,tag:jR/QpWMQ90puUzDUgm7RFw==,type:str]
    encrypted_regex: ^(access-key-id|secret-access-key|region)$
    version: 3.10.2
