apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: remarkable-cloud-token
  namespace: remarkable-ocr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: remarkable-cloud-token
    creationPolicy: Owner
  data:
    - secretKey: devicetoken
      remoteRef:
        key: remarkable/cloud-token
        property: devicetoken
