apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myscript-api
  namespace: remarkable-ocr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: myscript-api
    creationPolicy: Owner
  data:
    - secretKey: app_key
      remoteRef:
        key: myscript/api
        property: app_key
    - secretKey: hmac_key
      remoteRef:
        key: myscript/api
        property: hmac_key
