apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: unas-backup-check
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:MmYn7eOnidf/1C9RpJe9ZDQ1Cec=,iv:zXgDdesMHzjStatihuLAK7JeUfcNzQ9LN4NPdfDSWiI=,tag:WnI8CZXYUfhA5cn+XClHdA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:rxDUrubTNWpkC5Hc2ZNVwGTo0QFuKmrnOSxB2qe91htVY+L7YFImpw==,iv:R+zv4oHM8LcZIgV4kkkwGOOlDi0omNC8rO017T+2uas=,tag:GSQh7OIC1nSWPutu4Jy8lg==,type:str]
    region: ENC[AES256_GCM,data:nirdESGl+gBd,iv:lWgFZZHJk2TfZvuJecMYuJvc7yGA+KWMHWSuYwvC3JE=,tag:GEj/bm5ocxQd5UzgOmlPkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL1l6U2I1b0NwNlIzRmYw
            d0RadHRxRFBjcTkwbzBGV1owbXJ6V1laMFVjCnVPT1d3N2VnRmhaYXBWR21Dc1A3
            ZEtWM0dXUjlTQUNrTitoNUdBUDhHZVUKLS0tIGlRdVJ6c1hqMFRIOW9Na1ZSakdt
            elRoc2gwVWlmd3hLS0l1djRjeGlidVUK1SbKl0lMOKvK0wUkUyFMxvwCDYs6LO7S
            PJwk4Jk5vvTx2o5Koyr/l99tCpXZgrOiPJ/iaQq3uuR1zqa3HtqkMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T14:37:09Z"
    mac: ENC[AES256_GCM,data:N9zERaoTS2Mvjtu0x7ce2RBirF6uOPA8VHSvCHwQFZpKbka1KUYQ1ij9lHxXhNWlIzxkHZvLISvBQIV4/+dTbBXjtlBByzmxwi8yT5hhuooxhoJNUDodbjf7eqepNj6TjZBczxEQu3Oe2Hp007Kdvmk0v90mzVvdg7s+S3YDgt8=,iv:hAgwOeGYYkZLG2qKKYBLZVgd6qSu2tFNDWjwSMgg5h8=,tag:JuiWshEM3HHxlD4KMsPZlQ==,type:str]
    version: 3.13.3
