apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: amig-erp-secrets
  namespace: amig-erp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secrets-store
  target:
    name: amig-erp-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: amig-erp/database
        property: DATABASE_URL
    - secretKey: SECRET_KEY
      remoteRef:
        key: amig-erp/database
        property: SECRET_KEY
