apiVersion: v1
kind: Namespace
metadata:
  name: amig-erp
  labels:
    name: amig-erp
    app.kubernetes.io/part-of: amig-erp
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
