apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: social-media
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:D+4hT+8kJoRBpQsGSbdWbd7JjlQ=,iv:kaGtbseT9C2/wL+Uj/sQa3GXIHPBSCnqnK+jdbtRknM=,tag:6cmoCLawrtY7i/nIfuU7vQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:7CobSggZ+byl/IcIqxk7zEFrpRJTyGBG9zyKlP1MsenmN7k1TLhFsA==,iv:stjvhhtz2CM4Cl0038DirUECco/LqtoQtU2zjnstU2k=,tag:WECZfEi9Klmnyh8KJZ4FQQ==,type:str]
    region: ENC[AES256_GCM,data:CyZSmfbSu/pW,iv:tbsH2bQLU9EllCgkUsMxZasvc2D8OXNfOf8ObdU/OTA=,tag:KyRoXJwDoLSAYsSdf1ugmQ==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT3BpRm5oQThHcURlWTFm
            WkJ4YUQ3TWlUMXpHNGhtUU5BeitXOEFzaVZFCjJVUVJ0QWRVNS9jVXZyV2Q2NFdE
            blBZcnp1bUFnakNLTTN6S0NYYmRUMFEKLS0tIEhvUVUxMDFoWktOUk1INDhLSXht
            KzJORmNiaTN2Wk1pOHl3U3RORFFEZmcKj7dIBtCYtAs6ut/8Uu8UuSWpNELbh7lS
            BSd8eOSO8Fv0T1fjR6IK8/XKX7sFTWe5c1F4IKFQYHdTFGvG/LgVEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T14:56:20Z"
    mac: ENC[AES256_GCM,data:LPzUapCoWLh0ZWYHGUM3oC528O1baCJpPD6/qDEzpAJWncsv0ZKzGJfhqELdCSP2ZBFbJXKhgxSXr2cdHwooKb9YS3FEv6MKfx4l+5PeECHz+bEltRd1I3W3Sckz29PBd/zhhPqfkvGRiRVv/Gh+zYl6V3PbmpFyryFdPWtzrOw=,iv:w4n3ojDPNsceEJgMMlWIfPNGliUx+NJIKnxNXo5rucU=,tag:LtzjcloTKJfRfhezfJqqkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
