apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: vault-gateway
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:JY1bxU8iX5B7jzM5ZvCT0B5uMRQ=,iv:iYRN3Q0DX0Ak6EkMEufiP+AgScm+IpSdQJ7yoJI0j5M=,tag:+MW3ZP9RUEqnT2s2rvOn6A==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Q0vUucAsPoJgTDWSTK3QM4x/UP8lgFKcnabiu5ShJK1bND2yqeck9A==,iv:lVjExjZyZj7FTXtZJTHazcNUnjWF/E6yMSSpFJ1bfCo=,tag:RmHM3Tsrx4de4QqdiGdYRg==,type:str]
    region: ENC[AES256_GCM,data:bWkiGmiTKo11,iv:bFk8DtDfJ2LEZnO68k2xAxgilsPufmmpp8WjTBDI3QQ=,tag:BhNCdpt2fFGv2xrPAdfmkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVzYrM2RTc0tpWE9ta1Yw
            S1hUYjNrWDBPZGQwVkltdTAyQ2thRDdqa2hJCnQ0eno1eUpIaW5ERmJVWXg5d0Zv
            WmdZZU1ibTcwcWpjSjFkMFhkNFhrVm8KLS0tIDBwMDRSZExzUFY3dWp5Q1dRNzBx
            UzAzcEhuMGdLbW9UTlgrSGtYZVRVSVEKfa1ne9N7ep1PRpquswFiXWUyCNU3KGVc
            T8S3pkffR4jktprdtCQNspRBFpAXzgK7A7gB8U2++rt1f5Jq8TAu7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T13:58:01Z"
    mac: ENC[AES256_GCM,data:zWd/BZ3H7m3cUIl13pqag5Mbe6gldQBKBt3dF3ND8DwbM7BTuxmghJ7xsqfbQmBnwUVUOgx3TNDeLmkuF5Xm+/THcmjgJLxwOy4YLHpz0wtJOmV6rNn/gfEPqwpzX580QWCCSRf7Vv102dqaLaG665uB5lJv8iBdrGZxMq0yj6E=,iv:9YpXHO5hXiXg50zyD59g7cN3EG46RyYYET8h1VlJ20s=,tag:SlspsVlxhhI6G/q2qhUH3g==,type:str]
    version: 3.13.3
