apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobots-ui
  namespace: autobots
  labels:
    app: autobots-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autobots-ui
  template:
    metadata:
      labels:
        app: autobots-ui
    spec:
      containers:
        - name: autobots-ui
          image: lzetam/autobots-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: FEED_URL
              value: "http://autobots-feed.autobots.svc.cluster.local:8000/feed?limit=50"
            - name: NEXT_PUBLIC_UMAMI_WEBSITE_ID
              value: "49ba4b31-682e-47bf-b86c-f940fecf6234"
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      imagePullSecrets:
        - name: dockerhub-registry
