apiVersion: v1
kind: Service
metadata:
  name: ginger-hoa
  namespace: ginger-hoa
  labels:
    app.kubernetes.io/name: ginger-hoa
    app.kubernetes.io/part-of: ginger-hoa
spec:
  selector:
    app.kubernetes.io/name: ginger-hoa
  ports:
    - name: http
      port: 8000
      targetPort: http
