apiVersion: v1
kind: Namespace
metadata:
  name: ai-news
  labels:
    name: ai-news
    app.kubernetes.io/name: ai-news-pipeline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
