apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: unas-backup
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:tgai3IunfPXjs4k4RF3DDcMHmto=,iv:u4gCU7v6TK3j32opbetRNK8khOlDJVdUD0ZNE/PEcPA=,tag:CfY5N5XV7MRcWd3KrgEsnA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:6FGe3lHa0gDBqTDn5FOOMcinDE5k4t51WMrTPMxgY0Mz1poYU6Qmvw==,iv:xRxNil03ZUs6+XofWgm4P51/zwc+b2HoQIORsNubfNU=,tag:1sSFm/z/ia2qVRbANYxYfQ==,type:str]
    region: ENC[AES256_GCM,data:/cjJldDUItkp,iv:8NPm+5wn8Nzso5KaV0TvaSqHXmwab6W6a7Nbi9rbrz4=,tag:uxC7+BTzBK6YMaCTkA2Q4g==,type:str]
sops:
    age:
        - recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN3p5UFdCeC9LYy81d1Q1
            b05UTW9VbkEzbUVQaEkwaWhQQ3BTYUxPNkZBCncrV2NWVUg1dEl0T2xXYU9TZSt6
            dXpXTzBIME9waE1WdURRd3Rxb2FWREUKLS0tIDNSeW81OEZKUWZEZjdHZWdRMmVK
            RDlxZTEzTmI5NU5mWkRlSkVRSE5LR0UK2Ojcr5sOmPQOnsSB8C49l1YHgaO0w5/e
            Pe2a8q7FgRLTFn11HlXt/lROqueimC4y/Ofyx99bfbXjKq6VHyiwEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T13:49:44Z"
    mac: ENC[AES256_GCM,data:j02W/XFojqGWq40ABlemqA3Vao4DJ4r2S31+7bFsRgL/4v37+/lTIqQutsMtBk495kdctD1np3bahmg5uiklMSH+w/WOY46TxnUsdyo6tEq1NjsJsrPvzjJWgCL3P3fDPaQcMGYkGceFS2UdeUESKHJpUza5ayK7SxvDW37+hD8=,iv:ohqc/X0gA3+TxFwWbLL2vZ1ZS/wyPFqLW5PoIT4a9Ak=,tag:cRoDNmT1KgrRIk9ywfzLPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
