apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-secret-creator
  namespace: unas-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: docker-secret-manager
  namespace: unas-backup
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: docker-secret-creator-binding
  namespace: unas-backup
subjects:
- kind: ServiceAccount
  name: docker-secret-creator
  namespace: unas-backup
roleRef:
  kind: Role
  name: docker-secret-manager
  apiGroup: rbac.authorization.k8s.io
