apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-ca
  namespace: oura-collector
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDbjCCAlagAwIBAgIBATANBgkqhkiG9w0BAQsFADAiMSAwHgYDVQQDExdPYnNp
    ZGlhbiBMb2NhbCBSRVNUIEFQSTAeFw0yNjA3MTUxNDQyMDdaFw0yNzA3MTUxNDQy
    MDdaMCIxIDAeBgNVBAMTF09ic2lkaWFuIExvY2FsIFJFU1QgQVBJMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fRzLaajYio350QJpW1bpjY8Y+mc2NRn
    2QozMS8Mdf+/V1Rg8eOGW4ZxnBSaxnY1pSxy0rRgs/cdAgarLf3LKquqxgU8LJTD
    E5rt6sUbFrZGmWpfuI0Q5XUBIxH9+n9tnUO9OO+qc5nvGONmJBQsqmNA6sxMvkiN
    YY4OzRL8kqxCoZiyLUANh8Y8akqu++UQpYe1ub0OWA1JWo++6VnUDtLVxOFN/NAg
    67b8PoggzMUF6tfeAPEwchX1ow8SJpGeCVWXTx821puBUkDhZPeN2Uj6j55gkgyW
    y6UmkqtkSVNJmUUsoD6LHUMoCETeYTB9feU9/yaHUvapmUuvDPySWwIDAQABo4Gu
    MIGrMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgLEMDsGA1UdJQQ0MDIG
    CCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUFBwMEBggrBgEFBQcD
    CDARBglghkgBhvhCAQEEBAMCAPcwOAYDVR0RBDEwL4cEfwAAAYIcb2JzaWRpYW4t
    YXBpLmxhbmRyeXpldGFtLm5ldIIJbG9jYWxob3N0MA0GCSqGSIb3DQEBCwUAA4IB
    AQC/bZkTwBcz16xJiMFrE5g+dqAhbqrIyxUzjwlimHZ/v4EtEEUkW+hswNROeadd
    r+8L6OOPlQw+2qz0lO/d96GTRrbI9j4ONweZ3ehidANZbX1hyKaYYB1bXXmJAWiL
    H9+gg4N70F1BrP0gLB1e3jkuucqSuM2AX+UU9Fcuj7tD9VadBkDPGThVwtHLV2OT
    m4q8UIErdCZqUg031SO4pDKe1DhLA3e+hloWXHhIapuj6U1iJEQxr3ysXCmIRAAE
    G3sL79pm3wKqCkFRtnapr861vLht4yZrf0NElfdlYCgABjMesuR5PnH3F/mjflF6
    SN9i+Yvzuykiu8PttU6ZNpaw
    -----END CERTIFICATE-----
