apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oura-api-env
  namespace: oura-collector
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: oura-api-env
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        OURA_PERSONAL_ACCESS_TOKEN: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: oura/api-credentials
      property: oura_personal_access_token
  refreshInterval: 1h
