apiVersion: v1
kind: Secret
metadata:
    name: network-topology
    namespace: flux-system
type: Opaque
stringData:
    NODE_SUBNET: ENC[AES256_GCM,data:4epzLloFoFovNuy+yw==,iv:s306Y/Gmw7RQp3jakPzyHmqykKG76ODZ6XA57hsA1e4=,tag:GXyTRcNbi1Hlavm6pIE0Hw==,type:str]
    VAULT_SUBNET: ENC[AES256_GCM,data:ixQzsRi0qf0qPASyyg==,iv:GWRnu2VoUhqANFSOfuN3BR2vvcx05eu8z3PdHWOd15o=,tag:YITw6MOVbkv/4ENuKBNTww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZzFxK2JXVVB6MjhXUFAz
            L1lSSmttL3BVQ1k0S08zZWtIeVhUb3p5akVBCkQ3NzV3T1IvVkJ2MDBoUmtsdElP
            ZFNiVmNLQzZQSWc5VTBiQXoxL1k2TXMKLS0tIFhLYjkzS2xOczNuZ2lGTllaQVNB
            TWEzSFZ1ZmhuTVZlTUt4RzJIanE0aWsKvc3sRnGi5BhYPiIpBONAyWNa3yqE+iSA
            jQ/VxL8XfcDxp4RxlnhlAJzNqPFlCcbzQ4tzl2hF1nVDb133E8R+TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wz30c9m30hshgx9tg5lylctp646hgu3p0v0sxjuy8xxz34exh4hstn9utd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T15:43:33Z"
    mac: ENC[AES256_GCM,data:J5bhmhyPx5pBEfeLdwnOxzknzPXSs7jiaE1ljqeCWtWWhYfuisYa/hrbfQI5Q4pvi+dBYhE2mN3FAsG8IE3qSmIuS4kyI25X3S3QAmHVLwrUhmYRnTnu4PcHML4UAbFl9wWzA228rPauFzOxwLcG0Kv+9S6NT461x63k7SiI6WI=,iv:vtMVk2Pm3VGGT6cixM29M23TAJ/MfVc5ilmXTPiDp9k=,tag:TO4atAJx+gkc6G+0O8Cj4A==,type:str]
    version: 3.13.3
